import { Navigate, Route, Routes } from 'react-router-dom'
import StatusShell from './components/StatusShell'
import AccountView from './views/AccountView'
import StatusView from './views/StatusView'

const dictionaries = {
  zh: {
    locale: 'zh',
    languageToggle: { zh: '中文', en: 'EN' },
    shell: {
      productName: 'CPACodexKeeper',
      productSubtitle: '账户与状态概览',
      navStatus: '状态',
      navAccount: '账户',
    },
    shared: {
      enabled: '启用',
      disabled: '停用',
      loadingStatus: '正在加载状态...',
      loadingAccounts: '正在加载账户...',
      fallbackMessage: '等待下一次更新...',
      noExpiry: '无到期时间',
      pageSize: '每页数量',
      previous: '上一页',
      next: '下一页',
    },
    status: {
      online: '服务在线',
      title: '系统状态',
      description: '查看当前运行状态、刷新结果和账户可用性，快速了解这次状态同步是否稳定。',
      mode: '模式',
      updated: '更新时间',
      code: '代码',
      signalTitle: '当前信号',
      lastFinish: '最近完成时间',
      currentNotice: '当前提示',
      notice: '提示',
      standby: '待机',
      total: '总数',
      totalSubtitle: '全部账户对象',
      alive: '在线',
      aliveSubtitle: '当前可用节点',
      dead: '离线',
      deadSubtitle: '当前不可用节点',
      disabled: '停用',
      disabledSubtitle: '已停用节点',
      telemetryTitle: '刷新统计',
      telemetryBadge: '本次周期',
      refreshed: '已刷新',
      skipped: '已跳过',
      networkError: '网络错误',
      feedTitle: '活动概览',
      feedBadge: '最近 24 格',
      logsTitle: '状态明细',
      logsDescription: '保留本次状态快照中的关键时间点、模式和结果，便于快速核对。',
      logsLevel: '当前会话',
      logsTrace: '实时快照',
      parameter: '字段',
      valueStamp: '当前值',
      statusLabel: '状态',
      footerLocalTime: '本地时间',
      footerInterval: '刷新间隔',
      footerEnabled: '启用账户',
      footerSync: '同步正常',
      footerLink: '状态视图',
      footerVersion: '界面版本 4.0.1',
      logLabels: {
        STARTED_AT: '开始时间',
        UPDATED_AT: '更新时间',
        MODE: '运行模式',
        RESULT: '执行结果',
        INTERVAL: '刷新间隔',
        MESSAGE: '消息',
      },
      logStatuses: {
        INIT_OK: '已启动',
        SYNC_OK: '同步完成',
        SYNC_ACTIVE: '同步中',
        ACTIVE: '常驻',
        ONCE: '单次',
        TIMER: '定时',
        NOTICE: '提示',
        STANDBY: '待机',
      },
    },
    account: {
      online: '账户在线',
      title: '账户概览',
      description: '用更清晰的摘要、分页和卡片视图查看账户状态，快速确认可用容量和异常账户。',
      totalNodes: '总节点数',
      range: '显示范围',
      page: '页码',
      pageSize: '每页数量',
      enabledNodes: '启用账户',
      enabledDescription: '当前可参与路由的账户数量。',
      disabledNodes: '停用账户',
      disabledDescription: '暂不参与轮转的账户数量。',
      gridTitle: '账户列表',
      gridDescription: '保留现有数据语义，用更舒展的布局浏览当前账户。',
      visible: '当前可见',
      controlsTitle: '翻页控制',
      controlsDescription: '切换当前账户分页，同时保持现有功能行为。',
      controlBadge: '分页',
      defaultCapacity: '默认容量',
      gridRhythm: '网格节奏',
      liveTitle: '视图说明',
      liveBadge: '实时',
      liveEnabledSurface: '主要展示',
      liveEnabledSurfaceValue: '名称与状态',
      liveQuotaTracking: '配额追踪',
      liveQuotaTrackingValue: '主窗口与活跃窗口',
      liveTokenValidity: '凭证有效期',
      liveTokenValidityValue: '实时显示',
      footerView: '当前页面',
      footerMode: '展示模式',
      footerVisible: '可见卡片',
      footerReady: '账户就绪',
      footerStable: '显示稳定',
      footerViewValue: '账户',
      footerModeValue: '实时概览',
      card: {
        node: '账户名称',
        primaryQuota: '主配额',
        status: '状态',
        activeWindow: '活跃窗口',
        tokenExpiry: '到期时间',
      },
    },
  },
  en: {
    locale: 'en',
    languageToggle: { zh: '中文', en: 'EN' },
    shell: {
      productName: 'CPACodexKeeper',
      productSubtitle: 'Status and account overview',
      navStatus: 'Status',
      navAccount: 'Accounts',
    },
    shared: {
      enabled: 'Enabled',
      disabled: 'Disabled',
      loadingStatus: 'Loading status...',
      loadingAccounts: 'Loading accounts...',
      fallbackMessage: 'Waiting for the next refresh...',
      noExpiry: 'No expiry',
      pageSize: 'Page size',
      previous: 'Previous',
      next: 'Next',
    },
    status: {
      online: 'Service online',
      title: 'System status',
      description: 'Review the current run state, refresh results, and account availability at a glance.',
      mode: 'Mode',
      updated: 'Updated',
      code: 'Code',
      signalTitle: 'Current signal',
      lastFinish: 'Last completed',
      currentNotice: 'Current notice',
      notice: 'Notice',
      standby: 'Standby',
      total: 'Total',
      totalSubtitle: 'All account objects',
      alive: 'Healthy',
      aliveSubtitle: 'Available right now',
      dead: 'Offline',
      deadSubtitle: 'Currently unavailable',
      disabled: 'Disabled',
      disabledSubtitle: 'Excluded from rotation',
      telemetryTitle: 'Refresh summary',
      telemetryBadge: 'Current cycle',
      refreshed: 'Refreshed',
      skipped: 'Skipped',
      networkError: 'Network errors',
      feedTitle: 'Activity overview',
      feedBadge: 'Recent 24 slots',
      logsTitle: 'Status details',
      logsDescription: 'Keep the important timestamps, mode, and result of the active snapshot close at hand.',
      logsLevel: 'Current session',
      logsTrace: 'Live snapshot',
      parameter: 'Field',
      valueStamp: 'Value',
      statusLabel: 'State',
      footerLocalTime: 'Local time',
      footerInterval: 'Refresh interval',
      footerEnabled: 'Enabled accounts',
      footerSync: 'Sync healthy',
      footerLink: 'Status view',
      footerVersion: 'UI version 4.0.1',
      logLabels: {
        STARTED_AT: 'Started at',
        UPDATED_AT: 'Updated at',
        MODE: 'Mode',
        RESULT: 'Result',
        INTERVAL: 'Interval',
        MESSAGE: 'Message',
      },
      logStatuses: {
        INIT_OK: 'Started',
        SYNC_OK: 'Synced',
        SYNC_ACTIVE: 'Refreshing',
        ACTIVE: 'Daemon',
        ONCE: 'One-shot',
        TIMER: 'Timer',
        NOTICE: 'Notice',
        STANDBY: 'Standby',
      },
    },
    account: {
      online: 'Account channel online',
      title: 'Account overview',
      description: 'Use a clearer summary, pagination, and card layout to review account health and available capacity.',
      totalNodes: 'Total nodes',
      range: 'Range',
      page: 'Page',
      pageSize: 'Page size',
      enabledNodes: 'Enabled accounts',
      enabledDescription: 'Accounts currently available for routing.',
      disabledNodes: 'Disabled accounts',
      disabledDescription: 'Accounts currently held out of rotation.',
      gridTitle: 'Account list',
      gridDescription: 'Keep the current data semantics while browsing accounts in a calmer layout.',
      visible: 'Visible',
      controlsTitle: 'Pagination',
      controlsDescription: 'Move through the current account pages without changing the underlying behavior.',
      controlBadge: 'Paging',
      defaultCapacity: 'Default capacity',
      gridRhythm: 'Grid rhythm',
      liveTitle: 'View notes',
      liveBadge: 'Live',
      liveEnabledSurface: 'Primary view',
      liveEnabledSurfaceValue: 'Name and status',
      liveQuotaTracking: 'Quota tracking',
      liveQuotaTrackingValue: 'Primary and active window',
      liveTokenValidity: 'Token expiry',
      liveTokenValidityValue: 'Shown live',
      footerView: 'View',
      footerMode: 'Mode',
      footerVisible: 'Visible cards',
      footerReady: 'Accounts ready',
      footerStable: 'Display stable',
      footerViewValue: 'Account',
      footerModeValue: 'Live overview',
      card: {
        node: 'Account name',
        primaryQuota: 'Primary quota',
        status: 'Status',
        activeWindow: 'Active window',
        tokenExpiry: 'Token expiry',
      },
    },
  },
}

export default function App() {
  return (
    <Routes>
      <Route element={<StatusShell dictionaries={dictionaries} />}>
        <Route index element={<StatusView dictionaries={dictionaries} />} />
        <Route path="account" element={<AccountView dictionaries={dictionaries} />} />
      </Route>
      <Route path="*" element={<Navigate to="/" replace />} />
    </Routes>
  )
}
